### ISSUE TITLE
No longer builds under node 0.10.38

### ISSUE THREAD

**Issue by kdeol** [electronifie/node-quickfix#19]
```
> node-quickfix@0.6.0 preinstall /Users/kdeol/projects/node-quickfix
> npm install nan && node-gyp clean && node-gyp configure && node-gyp build

npm WARN package.json node-quickfix@0.6.0 No repository field.
npm WARN package.json nan@1.8.0 No README data
nan@1.8.0 node_modules/nan
  CXX(target) Release/obj.target/node_quickfix/src/FixSession.o
In file included from ../src/FixSession.cpp:9:
In file included from ../src/FixMessageUtil.h:15:
In file included from ../src/FixEvent.h:12:
../src/FixLoginResponse.h:30:18: warning: in-class initialization of non-static data member is a C++11 extension
      [-Wc++11-extensions]
        bool isFinished = false;
                        ^
../src/FixLoginResponse.h:31:18: warning: in-class initialization of non-static data member is a C++11 extension
      [-Wc++11-extensions]
        bool isLoggedOn = false;
                        ^
In file included from ../src/FixSession.cpp:9:
In file included from ../src/FixMessageUtil.h:15:
../src/FixEvent.h:24:30: warning: in-class initialization of non-static data member is a C++11 extension
      [-Wc++11-extensions]
        const FIX::Message* message = NULL;
                                    ^
../src/FixEvent.h:25:21: warning: in-class initialization of non-static data member is a C++11 extension
      [-Wc++11-extensions]
        NanCallback* logon = NULL;
                           ^
In file included from ../src/FixSession.cpp:9:
../src/FixMessageUtil.h:237:15: error: no viable conversion from 'Handle<v8::Object>' to 'Local<v8::Object>'
                                addJsTags(groupEntry, fields);
                                          ^~~~~~~~~~
/Users/kdeol/.node-gyp/0.10.38/deps/v8/include/v8.h:269:26: note: candidate constructor
      (the implicit copy constructor) not viable: cannot bind base class object of type 'Handle<v8::Object>' to
      derived class reference 'const v8::Local<v8::Object> &' for 1st argument
template <class T> class Local : public Handle<T> {
                         ^
/Users/kdeol/.node-gyp/0.10.38/deps/v8/include/v8.h:272:29: note: candidate template ignored: could not match
      'Local' against 'Handle'
  template <class S> inline Local(Local<S> that)
                            ^
/Users/kdeol/.node-gyp/0.10.38/deps/v8/include/v8.h:281:29: note: candidate template ignored: could not match
      'S *' against 'Handle<v8::Object>'
  template <class S> inline Local(S* that) : Handle<T>(that) { }
                            ^
../src/FixMessageUtil.h:196:42: note: passing argument to parameter 'msg' here
        static void addJsTags(Local<v8::Object> msg, const FIX::FieldMap* map) {
                                                ^
../src/FixMessageUtil.h:239:17: error: no viable conversion from 'Handle<v8::Object>' to 'Local<v8::Object>'
                                addJsGroups(groupEntry, fields);
                                            ^~~~~~~~~~
/Users/kdeol/.node-gyp/0.10.38/deps/v8/include/v8.h:269:26: note: candidate constructor
      (the implicit copy constructor) not viable: cannot bind base class object of type 'Handle<v8::Object>' to
      derived class reference 'const v8::Local<v8::Object> &' for 1st argument
template <class T> class Local : public Handle<T> {
                         ^
/Users/kdeol/.node-gyp/0.10.38/deps/v8/include/v8.h:272:29: note: candidate template ignored: could not match
      'Local' against 'Handle'
  template <class S> inline Local(Local<S> that)
                            ^
/Users/kdeol/.node-gyp/0.10.38/deps/v8/include/v8.h:281:29: note: candidate template ignored: could not match
      'S *' against 'Handle<v8::Object>'
  template <class S> inline Local(S* that) : Handle<T>(that) { }
                            ^
../src/FixMessageUtil.h:223:44: note: passing argument to parameter 'msg' here
        static void addJsGroups(Local<v8::Object> msg, const FIX::FieldMap* map) {
                                                  ^
4 warnings and 2 errors generated.
make: *** [Release/obj.target/node_quickfix/src/FixSession.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/kdeol/projects/node-quickfix
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! node-quickfix@0.6.0 preinstall: `npm install nan && node-gyp clean && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-quickfix@0.6.0 preinstall script.
npm ERR! This is most likely a problem with the node-quickfix package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install nan && node-gyp clean && node-gyp configure && node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-quickfix
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "link"
npm ERR! cwd /Users/kdeol/projects/node-quickfix
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/kdeol/projects/node-quickfix/npm-debug.log
npm ERR! not ok code 0
```

**Comment by stefankutko** [comment]
We've upgraded NAN and now support node 4+
