### ISSUE TITLE
Installing Module Fails

### ISSUE THREAD

**Issue by slamus** [electronifie/node-quickfix#48]
Hello,

First of all, thanks for this module 👍 

I've installed `quickfix` (SSL Fork) on OS X.
Then I installed the `'nan'` module (Had to guess for install error, so maybe add it to `README.MD`)
But when `node-gyp` starts compiling the binding I get this error:

```
> node-quickfix@2.1.1 install /Users/slamus/dev/fix-report/node_modules/node-quickfix
> node-gyp rebuild

  CXX(target) Release/obj.target/NodeQuickfix/src/FixSession.o
In file included from ../src/FixSession.cpp:9:
../src/FixMessageUtil.h:194:38: error: no member named 'first' in 'FIX::FieldBase'
                        header->Set(Nan::New<Integer>(it->first), Nan::New<v8::String>(it->second.getString().c_...
                                                      ~~  ^
../src/FixMessageUtil.h:194:71: error: no member named 'second' in 'FIX::FieldBase'
                        header->Set(Nan::New<Integer>(it->first), Nan::New<v8::String>(it->second.getString().c_...
                                                                                       ~~  ^
../src/FixMessageUtil.h:204:31: error: no viable conversion from '__wrap_iter<const_pointer>' to
      '__wrap_iter<pointer>'
                for(FIX::FieldMap::iterator it = map->begin(); it != map->end(); ++it)
                                            ^    ~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iterator:1258:7: note:
      candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const_iterator' (aka
      '__wrap_iter<const FIX::FieldBase *>') to 'const std::__1::__wrap_iter<FIX::FieldBase *> &' for 1st argument
class __wrap_iter
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iterator:1258:7: note:
      candidate constructor (the implicit move constructor) not viable: no known conversion from 'const_iterator' (aka
      '__wrap_iter<const FIX::FieldBase *>') to 'std::__1::__wrap_iter<FIX::FieldBase *> &&' for 1st argument
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iterator:1381:31: note:
      candidate constructor not viable: no known conversion from 'const_iterator' (aka
      '__wrap_iter<const FIX::FieldBase *>') to 'iterator_type' (aka 'FIX::FieldBase *') for 1st argument
    _LIBCPP_INLINE_VISIBILITY __wrap_iter(iterator_type __x) _NOEXCEPT_DEBUG : __i(__x) {}
                              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iterator:1280:28: note:
      candidate template ignored: disabled by 'enable_if' [with _Up = const FIX::FieldBase *]
        typename enable_if<is_convertible<_Up, iterator_type>::value>::type* = 0) _NOEXCEPT_DEBUG
                           ^
In file included from ../src/FixSession.cpp:9:
../src/FixMessageUtil.h:221:39: error: no member named 'first' in 'FIX::FieldBase'
                        trailer->Set(Nan::New<Integer>(it->first), Nan::New<v8::String>(it->second.getString().c...
                                                       ~~  ^
../src/FixMessageUtil.h:221:72: error: no member named 'second' in 'FIX::FieldBase'
                        trailer->Set(Nan::New<Integer>(it->first), Nan::New<v8::String>(it->second.getString().c...
                                                                                        ~~  ^
../src/FixMessageUtil.h:231:33: error: no viable conversion from 'g_const_iterator' (aka
      '__map_const_iterator<__tree_const_iterator<std::__1::__value_type<int, std::__1::vector<FIX::FieldMap *,
      std::__1::allocator<FIX::FieldMap *> > >, std::__1::__tree_node<std::__1::__value_type<int,
      std::__1::vector<FIX::FieldMap *, std::__1::allocator<FIX::FieldMap *> > >, void *> *, long> >') to
      'FIX::FieldMap::g_iterator' (aka '__map_iterator<__tree_iterator<std::__1::__value_type<int,
      std::__1::vector<FIX::FieldMap *, std::__1::allocator<FIX::FieldMap *> > >,
      std::__1::__tree_node<std::__1::__value_type<int, std::__1::vector<FIX::FieldMap *,
      std::__1::allocator<FIX::FieldMap *> > >, void *> *, long> >')
                for(FIX::FieldMap::g_iterator it = map->g_begin(); it != map->g_end(); ++it) {
                                              ^    ~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:685:28: note:
      candidate constructor (the implicit copy constructor) not viable: no known conversion from 'g_const_iterator' (aka
      '__map_const_iterator<__tree_const_iterator<std::__1::__value_type<int, std::__1::vector<FIX::FieldMap *,
      std::__1::allocator<FIX::FieldMap *> > >, std::__1::__tree_node<std::__1::__value_type<int,
      std::__1::vector<FIX::FieldMap *, std::__1::allocator<FIX::FieldMap *> > >, void *> *, long> >') to 'const
      std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<int, std::__1::vector<FIX::FieldMap *,
      std::__1::allocator<FIX::FieldMap *> > >, std::__1::__tree_node<std::__1::__value_type<int,
      std::__1::vector<FIX::FieldMap *, std::__1::allocator<FIX::FieldMap *> > >, void *> *, long> > &' for 1st argument
class _LIBCPP_TEMPLATE_VIS __map_iterator
                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:685:28: note:
      candidate constructor (the implicit move constructor) not viable: no known conversion from 'g_const_iterator' (aka
      '__map_const_iterator<__tree_const_iterator<std::__1::__value_type<int, std::__1::vector<FIX::FieldMap *,
      std::__1::allocator<FIX::FieldMap *> > >, std::__1::__tree_node<std::__1::__value_type<int,
      std::__1::vector<FIX::FieldMap *, std::__1::allocator<FIX::FieldMap *> > >, void *> *, long> >') to
      'std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<int, std::__1::vector<FIX::FieldMap *,
      std::__1::allocator<FIX::FieldMap *> > >, std::__1::__tree_node<std::__1::__value_type<int,
      std::__1::vector<FIX::FieldMap *, std::__1::allocator<FIX::FieldMap *> > >, void *> *, long> > &&' for 1st
      argument
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:703:5: note:
      candidate constructor not viable: no known conversion from 'g_const_iterator' (aka
      '__map_const_iterator<__tree_const_iterator<std::__1::__value_type<int, std::__1::vector<FIX::FieldMap *,
      std::__1::allocator<FIX::FieldMap *> > >, std::__1::__tree_node<std::__1::__value_type<int,
      std::__1::vector<FIX::FieldMap *, std::__1::allocator<FIX::FieldMap *> > >, void *> *, long> >') to
      'std::__1::__tree_iterator<std::__1::__value_type<int, std::__1::vector<FIX::FieldMap *,
      std::__1::allocator<FIX::FieldMap *> > >, std::__1::__tree_node<std::__1::__value_type<int,
      std::__1::vector<FIX::FieldMap *, std::__1::allocator<FIX::FieldMap *> > >, void *> *, long>' for 1st argument
    __map_iterator(_TreeIterator __i) _NOEXCEPT : __i_(__i) {}
    ^
../src/FixSession.cpp:28:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
                                callback->Call(1, argv);
                                          ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
1 warning and 6 errors generated.
make: *** [Release/obj.target/NodeQuickfix/src/FixSession.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/slamus/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/slamus/.nvm/versions/node/v6.11.4/bin/node" "/Users/slamus/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/slamus/dev/fix-report/node_modules/node-quickfix
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN fix-report@1.0.0 No description
npm WARN fix-report@1.0.0 No repository field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/slamus/.nvm/versions/node/v6.11.4/bin/node" "/Users/slamus/.nvm/versions/node/v6.11.4/bin/npm" "install" "-S" "node-quickfix"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-quickfix@2.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-quickfix@2.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-quickfix package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-quickfix
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-quickfix
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/slamus/dev/fix-report/npm-debug.log

```

I believe this is related to node/node-gyp/Xcode C++ version conflicts.

**Comment by slamus** [comment]
Up?

**Comment by sbabushkin** [comment]
Same error

**Comment by ahmadsn26** [comment]
same error 22 days and no one answered

**Comment by DushanMinic** [comment]
Getting the same error, cannot install node-quickfix. Has anyone come up with a solution for this?

**Comment by vodanh109** [comment]
Same error. Hope that someone can help. Thanks

**Comment by carvmarc** [comment]
I think only works till quickfix version 1.14.3, 
When a downgrade from  1.15.1 to 1.14.3  it worked

**Comment by rafipiccolo** [comment]
Can you please explain how u could downgrade and require ?

**Comment by jeromevonk** [comment]
@rafipiccolo instead of downloading the TAR of the last version, get version 1.14.3 from [here](https://sourceforge.net/projects/quickfix/files/quickfix/)

**Comment by joelparkerhenderson** [comment]
Solution with step by step instructions here: 
http://github.com/joelparkerhenderson/demo_node_quickfix

Thank you @carvmarc for the advice to change to 1.14.3; this solved the root cause.
